######################################################################
# Automatically generated by qmake (1.07a) Thu Jul 21 17:31:13 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += configuration.h sqlspruch.h
SOURCES += configuration.cpp main.cpp sqlspruch.cpp
